defaults:
  - method: rnn
  - logger: wandb
  - _self_

# new
model_1_pretrained_weights_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\outputs\2024-12-16\20-51-24 #2024-12-12\19-40-48
model_1_id: 147 #1950
# aged
model_2_pretrained_weights_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\outputs\2024-12-16\19-28-22
model_2_id: 609

num_workers: 8  # Number of workers for DataLoader
device: gpu

hydra:
  job:
    chdir: True
    