defaults:
  - method: rnn
  - logger: wandb
  - _self_

# new
model_1_pretrained_weights_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\outputs\2024-12-12\19-40-48
model_1_id: 1950
# aged
model_2_pretrained_weights_dir: C:\Users\s8940173\Dokumente\GitHub\RNN_Battery_Model\outputs\2024-12-12\22-29-29
model_2_id: 1998  #326 #378 #

num_workers: 8  # Number of workers for DataLoader
device: gpu

hydra:
  job:
    chdir: True
    